#!/bin/bash
WS=$(hyprctl activeworkspace -j | jq ".id")

hyprctl clients -j | jq -r "[.[] | select(.workspace.id == $WS)] | .[].address" |
while read addr; do
  hyprctl dispatch settiled address:$addr
done
